// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvyzqbewsdmzjzxqwxpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2eXpxYmV3c2Rtemp6eHF3eHBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Njc2NTEsImV4cCI6MjA3MTI0MzY1MX0.EtO1hI71E1UdobD_WpZerBoE9h4a1ZigJBcFBIPjga4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});